[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "jupyterlab_notification"
author = "Mariko Wakabayashi"
author-email = "mariko@mwkby.com"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]

